insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (1, 'Matelda Dunklee', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (2, 'Roderich Novello', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (3, 'Gerrie Kingaby', 'žensko striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (4, 'Daryn Goodhew', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (5, 'Cyrille Adaway', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (6, 'Dougy Jossel', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (7, 'Pietrek Hutfield', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (8, 'Ira Bazeley', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (9, 'Arin Kilfedder', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (10, 'Tybie Schaffel', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (11, 'Burton Ivoshin', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (12, 'Glen Kesby', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (13, 'Ulises Nairne', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (14, 'Flossi Sunley', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (15, 'Tripp Leavesley', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (16, 'Alphonse Samsworth', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (17, 'Emlen Hellewell', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (18, 'Reube Fernehough', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (19, 'Tarah Goadbie', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (20, 'Saunder Gerhts', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (21, 'Hunt Ximenez', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (22, 'Howey Lingley', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (23, 'Chris Kiltie', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (24, 'Neila Dusey', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (25, 'Joey Nealy', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (26, 'Augustin Lamont', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (27, 'Concordia Bello', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (28, 'Caitlin Nutty', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (29, 'Charlene Bernhardsson', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (30, 'Philomena McCann', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (31, 'Rae Mariault', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (32, 'Mollee Donner', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (33, 'Teri Lockner', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (34, 'Elyn Purse', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (35, 'Rhys Blakely', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (36, 'Hilarius Norkutt', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (37, 'Claudelle Fouracres', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (38, 'Basilio Whittuck', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (39, 'Rubina Filipov', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (40, 'Bellina Twidle', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (41, 'Pippo Howe', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (42, 'Nissa Schankelborg', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (43, 'Mervin Donisi', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (44, 'Brigit Basketfield', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (45, 'Willdon Byas', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (46, 'Ber Perrelli', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (47, 'Leroy Gorvin', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (48, 'Neille Livingstone', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (49, 'Ailsun Terrans', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (50, 'Tan Sherbrook', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (51, 'Rozalie Foynes', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (52, 'Culley Goggins', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (53, 'Ilysa Castro', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (54, 'Bobine Krienke', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (55, 'Petronilla McIntee', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (56, 'Terri Biggen', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (57, 'Emmy Waterhowse', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (58, 'Theodoric Tamplin', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (59, 'Jermaine Lanigan', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (60, 'Karolina Paulino', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (61, 'Boycey Janjusevic', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (62, 'Claiborn Hanwell', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (63, 'Claudelle McFetrich', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (64, 'Sybilla Dimitriou', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (65, 'Madelaine Wignall', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (66, 'Lawton Piggens', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (67, 'Janina Falkinder', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (68, 'Elysia Brameld', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (69, 'Lina Janc', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (70, 'Salaidh Ackeroyd', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (71, 'Audrie Haggidon', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (72, 'Brnaby Argue', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (73, 'Perceval Darrington', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (74, 'Sharl Sandry', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (75, 'Betsey Baston', 'žensko striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (76, 'Pennie Errington', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (77, 'Willy Strephan', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (78, 'Leda Caswell', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (79, 'Kenneth Chestnut', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (80, 'Valentino Bartley', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (81, 'Sara-ann Harron', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (82, 'Terry Lerwill', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (83, 'De witt Foxcroft', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (84, 'Charil Erickson', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (85, 'Siegfried Pedracci', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (86, 'Philis Bone', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (87, 'Leela Danilovich', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (88, 'Malanie Loughton', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (89, 'Brade Gregan', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (90, 'Jorry Terbeck', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (91, 'Orelle Dunrige', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (92, 'Eolande Baroch', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (93, 'Purcell Lengthorn', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (94, 'Florian O''Meara', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (95, 'Jethro Lackney', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (96, 'Zita Malin', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (97, 'Sammy Northidge', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (98, 'Kelly Rabat', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (99, 'Shirleen Ruske', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (100, 'Robinetta Robelet', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (101, 'Rosina Casoni', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (102, 'Lacie Orchart', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (103, 'Sonia Kingstne', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (104, 'Jeremiah Hammelberg', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (105, 'Gina Klewer', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (106, 'Sumner Juzek', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (107, 'Damaris Powder', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (108, 'Jennette Rickarsey', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (109, 'Ignaz Orrow', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (110, 'Jannel Cowup', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (111, 'Fabio Creaser', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (112, 'Aurthur Sagg', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (113, 'Wini Faunt', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (114, 'Leanora Hebner', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (115, 'Analise Aylmore', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (116, 'Kennan Gulliman', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (117, 'Vincenty Rehme', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (118, 'Frances Camacho', 'žensko striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (119, 'Marcy Silcock', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (120, 'Wright Danielkiewicz', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (121, 'Archibold Addionisio', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (122, 'Ellette Tupp', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (123, 'Rudiger Langthorne', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (124, 'Connie Cockerton', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (125, 'Demeter Musico', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (126, 'Angy Sorrill', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (127, 'Quillan McGurk', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (128, 'Andrey Vallis', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (129, 'Kariotta Bessent', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (130, 'Baily Mawson', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (131, 'Murielle Ranscome', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (132, 'Husain Alexandrou', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (133, 'Chicky Butt', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (134, 'Lindie Grellier', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (135, 'Roderich Calvard', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (136, 'Zared Mohamed', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (137, 'Janaya Downage', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (138, 'Annnora Longstaffe', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (139, 'Elna Akid', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (140, 'Beckie Dansken', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (141, 'Jareb Donan', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (142, 'Harper Wraight', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (143, 'Kelsey Jaggli', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (144, 'Lucilia Crookes', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (145, 'Rickey Bernardelli', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (146, 'Miguel Jiggen', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (147, 'Rey Mateescu', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (148, 'Florencia Mabe', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (149, 'Heath Woodington', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (150, 'Mavis Tolan', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (151, 'Zonda Fielden', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (152, 'Casandra Sangwin', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (153, 'Dagny Cavan', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (154, 'Martie Capozzi', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (155, 'Tamera Maciejewski', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (156, 'Alejandra Noller', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (157, 'Darci Jewson', 'lasersko odstranjevanje dlak');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (158, 'Denny Mostin', 'barvanje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (159, 'Phoebe Cosans', 'pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (160, 'Jerrine FitzAlan', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (161, 'Mechelle Butterley', 'depilacija bikini predela');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (162, 'Salomon Sowley', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (163, 'Leoine Fance', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (164, 'Celisse Tugman', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (165, 'Westleigh Miguet', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (166, 'Stavros Dunlop', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (167, 'Valentin Alstead', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (168, 'Harlan Franzettoini', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (169, 'Broddie Shalloe', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (170, 'Phil Tremolieres', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (171, 'Ottilie Fabbri', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (172, 'Emlyn Le febre', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (173, 'Haily Grewes', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (174, 'Yolane Band', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (175, 'Benjy Dondon', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (176, 'Ceil Guitt', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (177, 'Drake Lillistone', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (178, 'Maurine Behne', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (179, 'Darren Mirando', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (180, 'Barnebas Delacour', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (181, 'Scotty Teffrey', 'podaljševanje trepalnic');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (182, 'Hedvig Siley', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (183, 'Sharity Alman', 'medicinska pedikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (184, 'Alvera Gouch', 'depilacija nog');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (185, 'Joyann Damerell', 'depilacija celotnega telesa');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (186, 'Reina Salaman', 'urejanje brade');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (187, 'Hakim Laurentin', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (188, 'Hermina Langlands', 'laminacija obrvi');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (189, 'Tadeo Cattel', 'manikura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (190, 'Geralda Thynne', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (191, 'Cary Pozer', 'žensko striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (192, 'Angele Dilworth', 'ličenje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (193, 'Georgy Brindley', 'moško striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (194, 'Lenka Malyj', 'depilacija pazduh');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (195, 'Babs Catto', 'masaža');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (196, 'Theo Pashbee', 'fen frizura');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (197, 'Bridie Maseyk', 'žensko striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (198, 'Lynnell Cornes', 'nega las in lasišča');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (199, 'Brynna Aiskrigg', 'žensko striženje');
insert into usluzbenec (id_usluzbenec, ime_priimek, ime_storitve) values (200, 'Abby Pechard', 'lasersko odstranjevanje dlak');
