insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (93, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (41, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (197, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (156, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (28, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (200, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (46, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (121, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (155, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (200, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (187, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (90, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (25, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (182, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (128, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (27, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (22, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (153, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (68, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (108, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (158, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (101, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (163, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (104, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (13, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (123, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (64, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (54, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (108, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (3, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (184, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (167, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (54, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (73, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (40, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (133, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (20, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (157, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (77, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (42, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (15, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (37, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (18, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (179, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (124, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (105, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (178, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (173, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (82, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (147, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (132, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (35, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (39, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (192, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (181, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (109, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (35, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (34, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (94, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (44, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (61, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (170, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (32, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (28, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (1, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (188, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (40, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (50, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (44, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (1, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (2, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (82, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (78, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (98, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (25, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (146, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (175, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (98, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (146, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (158, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (162, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (145, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (20, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (193, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (139, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (176, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (140, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (188, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (97, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (105, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (114, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (188, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (86, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (123, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (84, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (128, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (77, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (132, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (146, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (158, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (72, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (18, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (161, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (199, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (152, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (108, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (176, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (139, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (130, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (99, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (129, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (120, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (109, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (189, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (162, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (54, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (39, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (164, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (190, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (94, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (56, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (32, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (14, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (152, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (64, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (19, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (42, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (15, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (12, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (166, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (37, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (113, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (152, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (162, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (180, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (174, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (118, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (50, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (183, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (168, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (98, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (76, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (96, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (177, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (101, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (158, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (195, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (57, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (34, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (16, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (81, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (38, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (4, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (86, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (26, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (19, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (71, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (173, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (31, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (62, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (26, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (44, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (53, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (101, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (93, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (170, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (2, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (15, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (9, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (84, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (152, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (40, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (153, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (39, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (71, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (143, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (18, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (111, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (21, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (199, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (112, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (68, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (122, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (54, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (70, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (187, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (155, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (162, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (151, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (14, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (194, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (126, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (103, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (126, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (99, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (57, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (68, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (174, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (87, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (197, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (54, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (78, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (139, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (3, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (20, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (45, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (97, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (104, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (69, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (37, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (191, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (23, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (139, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (195, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (76, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (183, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (79, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (190, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (125, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (1, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (148, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (186, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (125, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (148, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (44, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (95, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (164, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (6, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (29, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (116, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (187, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (50, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (76, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (139, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (107, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (49, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (48, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (172, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (165, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (75, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (169, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (150, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (149, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (71, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (148, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (100, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (136, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (187, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (4, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (57, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (148, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (13, 'laminacija obrvi');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (7, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (173, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (117, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (80, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (39, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (169, 'podaljševanje trepalnic');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (34, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (58, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (98, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (17, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (145, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (73, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (176, 'depilacija celega telesa');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (85, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (164, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (148, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (48, 'urejanje brade');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (186, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (46, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (146, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (124, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (159, 'manikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (60, 'lasersko odstranjevanje dlak');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (175, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (130, 'masaža');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (98, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (9, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (199, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (70, 'nega las in lasišča');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (39, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (172, 'ličenje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (138, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (11, 'medicinska pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (183, 'moško striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (83, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (146, 'fen frizura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (142, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (2, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (76, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (150, 'barvanje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (81, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (95, 'žensko striženje');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (183, 'depilacija pazduh');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (49, 'depilacija nog');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (148, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (80, 'depilacija bikini predela');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (44, 'pedikura');
insert into usluzb_storitve (id_usluzbenec, ime_storitve) values (45, 'pedikura');
